### ISSUE TITLE
Update for 1.20.1?

### ISSUE THREAD

**Issue by Lou9896** [matthewperiut/StitchedSnow#11]
Will this mod ever be updated?

**Comment by matthewperiut** [comment]
Sure I can, but take a look into `/gamerule snowAccumulationHeight` which was added in 1.19.3 first because it is very similar, and it's in the vanilla game. Let me know if that isn't sufficient, but evidently the last version of the mod is 1.19.2 because i saw this and was like cool, its in vanilla now.

**Comment by solonovamax** [comment]
oh I keep forgoring to push the changes 💀

**Comment by solonovamax** [comment]
also, `snowAccumulationHeight` isn't as cool and epic as my implementation lol

**Comment by matthewperiut** [comment]
Yes well the implementation the mod has done is more snow next to blocks, and vanilla doesn't do that. What type of behavior does your version do exactly?

**Comment by Lou9896** [comment]
Yeah I would love to get a better version of what is in Vanilla as it doesn't do the snow justice like this mod did

**Comment by Lou9896** [comment]
> Sure I can, but take a look into `/gamerule snowAccumulationHeight` which was added in 1.19.3 first because it is very similar, and it's in the vanilla game. Let me know if that isn't sufficient, but evidently the last version of the mod is 1.19.2 because i saw this and was like cool, its in vanilla now.

yea that command is ass. It just plies snow up everywhere and doesn't give the snow the varying heights

**Comment by solonovamax** [comment]
Updates released on modrinth and curseforge for 1.19.4-1.20.1 and 1.20.4.

I have not tested 1.20.2 or 1.20.3, but one of those two versions may work for it.
