### ISSUE TITLE
Requies client side

### ISSUE THREAD

**Issue by Warp159** [matthewperiut/StitchedSnow#15]
after instlain on server if players didnt have it on client a lot of blocks get tranformed in another only as visual. @
![image](https://github.com/user-attachments/assets/79dddf8c-cd27-4dde-a84d-20419a019d0e)

![image_2024-12-01_181247222](https://github.com/user-attachments/assets/e36e2481-f51c-44a1-b127-d170ba20b742)

**Comment by solonovamax** [comment]
I'm unsure what the particular issue you're attempting to point out is, however it is not required client-side.
I've run it myself on a server without the matching client-side mod.

Can you reproduce this issue with *only* this mod installed?

**Comment by solonovamax** [comment]
nvm, it seems that in 98a924e some changes were made which adds a new property to the snow layers. I'll try and look into this later.

**Comment by RainbowwwJ** [comment]
any updates on this? I'm experiencing the same issue

**Comment by solonovamax** [comment]
sorry, I never got around to it, I'll try to look at it in a few hours.

**Comment by solonovamax** [comment]
Release has been uploaded to both modrinth and to curseforge.
