### ISSUE TITLE
TPS Issues #159 

### ISSUE THREAD

**Issue by kittech0** [matthewperiut/StitchedSnow#2]
(copy of https://github.com/StrikerRockers-Mods/VanillaTweaks/issues/159)
so basically your mod couses a lower TPS, literally unplayable
**Spark**: https://spark.lucko.me/BLhTCGxXBB
I'm playing on 1.18.1 Fabric on latest version

**Comment by eputty123** [comment]
what other mods are running? I didn't have this issue.

**Comment by kittech0** [comment]
I'm running my own modpack, this is last version that had stitched snow mod https://github.com/JustFoxx/Adventures-Of-Fox-Beginning-Of-A-Journey/releases/tag/a0.2.5
