### ISSUE TITLE
Ticking crash on 1.18.2 with version 1.0.4

### ISSUE THREAD

**Issue by eputty123** [matthewperiut/StitchedSnow#3]
Server crash with tick exception on 1.18.2 latest fabric version and loader, probably due to the changes made in 1.18.2 to tags as this wasn't ever an issue in prior versions. Here's the crash log and server log. it appears the first log tried to stop the crash and failed.
[crash-2022-03-08_01.32.09-server.txt](https://github.com/matthewperiut/StitchedSnow/files/8204729/crash-2022-03-08_01.32.09-server.txt)
[latest.log](https://github.com/matthewperiut/StitchedSnow/files/8204771/latest.log)
.

**Comment by byquanton** [comment]
I updated the Mod to 1.18.2 (#4).
[stitched-snow-1.0.4.jar](https://github.com/byquanton/StitchedSnow/releases/download/1.18.2/stitched-snow-1.0.4.jar)
