### ISSUE TITLE
Will you be updating the mod for 1.20?

### ISSUE THREAD

**Issue by LordBloodbath** [matthewperiut/StitchedSnow#9]
Will you be updating the mod for 1.20? I hope very much!

**Comment by Lou9896** [comment]
Same the game is not the same with out this mod

**Comment by solonovamax** [comment]
Updates released on modrinth and curseforge for 1.19.4-1.20.1 and 1.20.4.

I have not tested 1.20.2 or 1.20.3, but one of those two versions may work for it.
